/**
 * Database schema — TypeScript interfaces for the full game save state
 *
 * This file defines the "shape" of the savegame.json file persisted by LowDB.
 * All Decimal values are stored as SerializedDecimal { m, e }.
 * Version field enables forward-compatible migrations.
 *
 * IMPORTANT: The actual save format is dynamically generated by
 * `collectGameState()` in useAutoSave.ts. This schema serves as documentation
 * and for the createDefaultSave() factory. The renderer stores drive the
 * true data shapes. If you update store state structures, update collectGameState()
 * and initGame() accordingly — the schema types here are advisory.
 */

// ─── Serialized Decimal (for JSON persistence) ─────────────────────

export interface SD {
  /** Discriminant tag — distinguishes Decimals from arbitrary {m, e} objects */
  __d?: 1
  m: number
  e: number
}

// ─── Player ─────────────────────────────────────────────────────────

export interface PlayerSave {
  cash: SD
  totalCashEarned: SD
  totalCashSpent: SD
  /** Total prestige points (persisted across rebirths) */
  prestigePoints: SD
  /** Total rebirth count */
  rebirthCount: number
  /** XP / level for the player character */
  level: number
  xp: SD
  xpToNextLevel: SD
  /** Pre-computed net worth */
  netWorth: SD
}

// ─── Businesses ─────────────────────────────────────────────────────

export interface BusinessSave {
  id: string
  name: string
  description: string
  icon: string
  category: string
  // Operational levers
  employees: number
  pricePerUnit: number
  marketingBudget: number
  quality: number
  // Fixed from definition
  outputPerEmployee: number
  baseSalary: number
  baseRent: number
  supplyCostPerUnit: number
  optimalPrice: number
  baseCustomers: number
  elasticity: number
  sectorMultiplier: number
  qualityUpgradeCost: SD
  purchasePrice: SD
  // Tracked stats
  totalRevenue: SD
  totalCosts: SD
  totalProfit: SD
  avgProfitPerTick: SD
  ticksOwned: number
}

// ─── Jobs ───────────────────────────────────────────────────────────

export interface ActiveJobSave {
  id?: string
  defId: string
  experienceLevel: number
  ticksWorked: number
  active: boolean
}

export interface JobsSave {
  unlockedJobs: ActiveJobSave[]
}

// ─── Economy ────────────────────────────────────────────────────────

export interface EconomySave {
  inflationRate: number
  inflationIndex: number
  interestRate: number
  consumerConfidence: number
  wageIndex: number
  cyclePhase: string
  cycleTicksElapsed: number
  cyclePhaseDuration: number
  totalTicks: number
  taxRate: number
}

// ─── Stocks ─────────────────────────────────────────────────────────

export interface PortfolioPositionSave {
  assetId: string
  shares: number
  averageBuyPrice: number
  totalInvested: SD
}

export interface StockSave {
  portfolio: PortfolioPositionSave[]
  /** Market simulator serialized state */
  marketState: unknown
  totalRealizedProfit: SD
  totalDividendsEarned: SD
}

// ─── Crypto ─────────────────────────────────────────────────────────

export interface CryptoHoldingSave {
  assetId: string
  amount: number
  averageBuyPrice: number
  totalInvested: SD
}

export interface CryptoSave {
  wallet: CryptoHoldingSave[]
  marketState: unknown
  totalRealizedProfit: SD
}

// ─── Loans ──────────────────────────────────────────────────────────

export interface ActiveLoanSave {
  id: string
  loanDefId: string
  principal: SD
  remaining: SD
  effectiveRate: number
  minPaymentPerTick: SD
  totalPaid: SD
  totalInterestPaid: SD
  principalPaid: SD
  startTick: number
  ticksActive: number
  termTicks: number
  collateralType: string | null
  collateralId?: string | null
  collateralLocked: SD
  ticksSinceLastPayment: number
  ticksLate: number
  isDefaulted: boolean
  onTimePayments: number
  latePayments: number
  missedPayments: number
}

export interface CreditScoreFactorsSave {
  paymentHistory: number
  creditUtilization: number
  creditAge: number
  creditMix: number
  newCredit: number
}

export interface LoanHistoryEntrySave {
  loanDefId: string
  principal: SD
  totalInterestPaid: SD
  startTick: number
  endTick: number
  status: 'repaid' | 'defaulted' | 'refinanced'
  onTimePayments: number
  latePayments: number
}

export interface LoansSave {
  loans: ActiveLoanSave[]
  creditScore: number
  creditScoreFactors: CreditScoreFactorsSave
  loanHistory: LoanHistoryEntrySave[]
  totalTicksWithCredit: number
  recentApplications: number[]
  totalLoansTaken: number
  totalLoansRepaidOnTime: number
  totalLoansDefaulted: number
  totalInterestPaidEver: SD
}

// ─── Deposits ───────────────────────────────────────────────────────

export interface ActiveDepositSave {
  id: string
  depositDefId: string
  principal: SD
  currentBalance: SD
  totalInterestEarned: SD
  effectiveAPY: number
  startTick: number
  termTicks: number
  ticksActive: number
  matured: boolean
  loyaltyActive: boolean
  ticksSinceLastCompound: number
  totalCompounds: number
  closed: boolean
  loyaltyTicks: number
}

export interface DepositHistoryEntrySave {
  depositDefId: string
  principal: SD
  totalInterestEarned: SD
  effectiveAPY: number
  ticksHeld: number
  matured: boolean
  earlyWithdrawal: boolean
  penaltyPaid: SD
  status: 'completed' | 'withdrawn_early' | 'closed_at_maturity'
}

export interface DepositsSave {
  deposits: ActiveDepositSave[]
  depositHistory: DepositHistoryEntrySave[]
  totalDeposited: SD
  totalInterestEarnedEver: SD
  totalDepositsOpened: number
  totalDepositsMatured: number
  totalEarlyWithdrawals: number
}

// ─── Real Estate (export state) ─────────────────────────────────────

export interface PropertySave {
  id: string
  locationId: string
  upgradeLevel: number
  purchasePrice: SD
  currentValue: SD
  baseRent: SD
  ownedSinceTick: number
  totalRentEarned: SD
}

export interface RealEstateStateSave {
  properties: PropertySave[]
  opportunities: Array<Record<string, unknown>>
  lastRefreshTick: number
  scannedDistricts?: Array<{ districtId: string; cooldownUntilTick: number }>
  totalPropertiesBought: number
  totalPropertiesSold: number
  totalRentEarned: SD
  totalMaintenancePaid: SD
  totalSaleProfit: SD
  totalImprovementsInstalled: number
}

// ─── Startups (export state) ────────────────────────────────────────

export interface StartupInvestmentSave {
  id: string
  startupId: string
  investedAmount: SD
  investedAtTick: number
  /** Ticks until resolution */
  maturityTicks: number
  /** Current status */
  status: 'active' | 'succeeded' | 'failed' | 'exited'
  returnMultiplier: number
}

export interface StartupStateSave {
  opportunities: Array<Record<string, unknown>>
  investments: StartupInvestmentSave[]
  lastRefreshTick: number
  totalInvested: SD
  totalReturned: SD
  sectorBonuses: Record<string, number>
  globalSuccessBonus: number
  globalReturnBonus: number
  successfulCount: number
  failedCount: number
}

// ─── Storage Wars (export state) ────────────────────────────────────

export interface StorageStateSave {
  [key: string]: unknown
}

// ─── Gambling ───────────────────────────────────────────────────────

export interface GamblingSave {
  totalBet: SD
  totalWon: SD
  totalLost: SD
  gamesPlayed: number
  biggestWin: SD
  biggestLoss: SD
  /** Per mini-game stats */
  gameStats: Record<string, { played: number; won: number; netProfit: SD }>
  /** Divine abilities unlocked via lottery */
  divineAbilities: string[]
  /** Lottery jackpot wins tracking */
  lotteryWins: Record<string, boolean>
}

// ─── Upgrades / Skill tree ──────────────────────────────────────────

export interface UpgradeNodeSave {
  id: string
  level: number
  maxLevel: number
  purchased: boolean
}

export interface UpgradeSave {
  nodes: UpgradeNodeSave[]
}

// ─── Achievements ───────────────────────────────────────────────────

export interface AchievementSave {
  id: string
  unlocked: boolean
  unlockedAtTick: number | null
}

// ─── Prestige ───────────────────────────────────────────────────────

export interface PrestigeUpgradeSave {
  id: string
  level: number
}

export interface PrestigeMilestoneSave {
  id: string
  unlocked: boolean
  unlockedAtTick: number | null
}

export interface PrestigePerkSave {
  id: string
  purchased: boolean
  purchasedAtTick: number | null
}

export interface PrestigeSave {
  points: SD
  totalPointsEarned: SD
  rebirthCount: number
  upgrades: PrestigeUpgradeSave[]
  milestones: PrestigeMilestoneSave[]
  perks: PrestigePerkSave[]
}

// ─── Events ─────────────────────────────────────────────────────────

export interface EventsSave {
  activeEvents: Array<{
    eventId: string
    ticksRemaining: number
    startedAt: number
    effects: Array<{ type: string; value: number; target?: string }>
  }>
  cooldowns: Record<string, number>
  pendingChoices: string[]
  totalTicks: number
}

// ─── Settings ───────────────────────────────────────────────────────

export interface SettingsSave {
  /** Locale code */
  locale: string
  /** Auto-save interval in seconds */
  autoSaveInterval: number
  /** Offline progress efficiency override */
  offlineEfficiency: number
  /** Max offline hours */
  offlineMaxHours: number
  /** Enable offline progress */
  offlineProgress: boolean
  /** Sound volume 0-100 */
  soundVolume: number
  /** Music volume 0-100 */
  musicVolume: number
  /** Enable notifications */
  notificationsEnabled: boolean
  /** Number format: 'short' (1.23M) | 'scientific' (1.23e6) | 'engineering' (1.23E6) */
  numberFormat: 'short' | 'scientific' | 'engineering'
  /** Theme: 'dark' | 'light' */
  theme: 'dark' | 'light'
  /** Animation speed multiplier (0.5, 1.0, 2.0) */
  animationSpeed: number
  /** Lottery draw speed multiplier */
  lotteryDrawSpeed: number
  /** Lottery multi-draw count */
  lotteryMultiDraw: number
  /** GitHub PAT for cloud saves (encrypted, stored separately) */
  cloudSaveEnabled: boolean
  /** Gist ID for cloud saves */
  gistId: string | null
  /** Buy amount mode */
  buyAmount: 1 | 10 | 25 | 100 | 'max'
  /** Show confirmation dialogs for big purchases */
  confirmBigPurchases: boolean
  /** Threshold for "big purchase" confirmation (as a % of total cash) */
  bigPurchaseThreshold: number
  /** Confirm before prestige */
  confirmPrestige: boolean
  /** Show tooltips on hover */
  showTooltips: boolean
  /** Particle/visual effects */
  particleEffects: boolean
  /** Market update frequency in game ticks */
  marketUpdateInterval: number
  /** Pinned stock for dashboard */
  pinnedStockId: string | null
  /** Pinned crypto for dashboard */
  pinnedCryptoId: string | null
}

// ─── Black Market (export state) ────────────────────────────────────

export interface BlackMarketEffectSave {
  id: string
  sourceId: string
  type: string
  value: number
  ticksRemaining: number
  totalDuration: number
  target?: string
}

export interface BlackMarketInvestigationSave {
  id: string
  nameKey: string
  severity: number
  ticksRemaining: number
  totalDuration: number
  fineAmount: SD
  catchChance: number
  resolved: boolean
  caught: boolean
}

export interface BlackMarketSave {
  totalDealsCompleted: number
  totalDealsFailed: number
  reputationPoints: number
  heat: number
  dealCooldowns: Record<string, number>
  lastDealRotationTick: number
  nextRotationTick: number
  contactStates: Array<Record<string, unknown>>
  activeEffects: BlackMarketEffectSave[]
  investigations: BlackMarketInvestigationSave[]
  totalCashSpent: SD
  totalCashEarned: SD
  totalHeatAccumulated: number
  totalInvestigations: number
  totalFinesPaid: SD
  lastTickProcessed: number
  activityLog: Array<Record<string, unknown>>
  availableDeals: Array<Record<string, unknown>>
}

// ─── Vault (export state) ───────────────────────────────────────────

export interface VaultItemSave {
  id: string
  name: string
  icon: string
  category: string
  rarity: string
  baseValue: SD
  description: string
  appraised: boolean
  appraisedValue: SD | null
  weight: number
  source: string
  vaultedAtTick: number
}

export interface VaultSave {
  items: VaultItemSave[]
  storedCash: SD
  capacityUpgrades: number
  totalItemsStored: number
  totalItemsSold: number
  totalSaleRevenue: SD
  totalCashDeposited: SD
  totalCashWithdrawn: SD
}

// ─── Shop (export state) ────────────────────────────────────────────

export interface ShopListingSave {
  id: string
  item: {
    id: string
    name: string
    icon: string
    category: string
    rarity: string
    baseValue: SD
    description: string
    appraised: boolean
    appraisedValue: SD | null
    weight: number
    condition?: string
  }
  price: SD
  basePrice: SD
  flashSale: boolean
  discount: number
  unique: boolean
  listedAtTick: number
  views: number
}

export interface ShopSave {
  listings: ShopListingSave[]
  purchasedUniqueIds: string[]
  lastRefreshTick: number
  lastFullRestockTick: number
  totalItemsBought: number
  totalCashSpentOnPurchases: SD
  totalItemsSoldToShop: number
  totalCashFromSales: SD
  uniqueItemsBought: number
  bestDeal: SD
  totalItemsRestored: number
  totalRestorationCashSpent: SD
  totalAuctionRevenue: SD
  totalAuctionsCompleted: number
  demands: Array<Record<string, unknown>>
  lastDemandTick: number
  restorationSlotCount: number
  restorationSlots: Array<Record<string, unknown> | null>
  activeAuctions: Array<Record<string, unknown>>
  auctionHistory: Array<Record<string, unknown>>
}

// ─── Root Save Schema ───────────────────────────────────────────────

export interface GameSave {
  /** Schema version for migrations */
  version: number
  /** Timestamp of this save (ms since epoch) */
  savedAt: number
  /** Total ticks played */
  totalTicks: number
  /** Total real-time played (seconds) */
  totalPlayTime: number

  player: PlayerSave
  businesses: BusinessSave[]
  jobs: JobsSave
  economy: EconomySave

  // Stocks — flat structure matching autoSave output
  stockPortfolio: PortfolioPositionSave[]
  stockStats: { totalRealizedProfit: SD; totalDividendsEarned: SD }
  stockMarketState: unknown

  // Crypto — flat structure matching autoSave output
  cryptoWallet: CryptoHoldingSave[]
  cryptoStats: { totalRealizedProfit: SD }
  cryptoMarketState: unknown

  // Real estate — uses exportState() which returns a full state object
  realEstate: RealEstateStateSave | PropertySave[]
  // Startups — uses exportState() which returns a full state object
  startups: StartupStateSave

  gambling: GamblingSave
  upgrades: UpgradeNodeSave[]
  achievements: AchievementSave[]
  prestige: PrestigeSave

  /** Event system state */
  eventState: EventsSave

  /** Loan system state */
  loans: LoansSave
  /** Deposit system state */
  deposits: DepositsSave

  /** Storage Wars state */
  storage?: StorageStateSave

  /** Black Market state */
  blackmarket?: BlackMarketSave

  /** Vault state */
  vault?: VaultSave

  /** Shop state */
  shop?: ShopSave

  settings: SettingsSave
}

/** Current schema version. Increment when making breaking changes. */
export const CURRENT_SAVE_VERSION = 3

// ─── Default / factory ──────────────────────────────────────────────

const ZERO_SD: SD = { m: 0, e: 0 }

export function createDefaultSave(): GameSave {
  return {
    version: CURRENT_SAVE_VERSION,
    savedAt: Date.now(),
    totalTicks: 0,
    totalPlayTime: 0,

    player: {
      cash: { m: 5, e: 1 }, // $50 starting cash
      totalCashEarned: { m: 5, e: 1 }, // Match store default
      totalCashSpent: ZERO_SD,
      prestigePoints: ZERO_SD,
      rebirthCount: 0,
      level: 1,
      xp: ZERO_SD,
      xpToNextLevel: { m: 1, e: 2 }, // 100
      netWorth: { m: 5, e: 1 }
    },

    businesses: [],

    jobs: {
      unlockedJobs: []
    },

    economy: {
      inflationRate: 0.02,
      inflationIndex: 1.0,
      interestRate: 0.05,
      consumerConfidence: 1.0,
      wageIndex: 1.0,
      cyclePhase: 'expansion',
      cycleTicksElapsed: 0,
      cyclePhaseDuration: 3000,
      totalTicks: 0,
      taxRate: 0.15
    },

    stockPortfolio: [],
    stockStats: {
      totalRealizedProfit: ZERO_SD,
      totalDividendsEarned: ZERO_SD
    },
    stockMarketState: null,

    cryptoWallet: [],
    cryptoStats: {
      totalRealizedProfit: ZERO_SD
    },
    cryptoMarketState: null,

    realEstate: {
      properties: [],
      opportunities: [],
      lastRefreshTick: 0,
      scannedDistricts: [],
      totalPropertiesBought: 0,
      totalPropertiesSold: 0,
      totalRentEarned: ZERO_SD,
      totalMaintenancePaid: ZERO_SD,
      totalSaleProfit: ZERO_SD,
      totalImprovementsInstalled: 0
    },

    startups: {
      investments: [],
      opportunities: [],
      lastRefreshTick: 0,
      totalInvested: ZERO_SD,
      totalReturned: ZERO_SD,
      sectorBonuses: {},
      globalSuccessBonus: 0,
      globalReturnBonus: 1,
      successfulCount: 0,
      failedCount: 0
    },

    gambling: {
      totalBet: ZERO_SD,
      totalWon: ZERO_SD,
      totalLost: ZERO_SD,
      gamesPlayed: 0,
      biggestWin: ZERO_SD,
      biggestLoss: ZERO_SD,
      gameStats: {},
      divineAbilities: [],
      lotteryWins: {}
    },

    upgrades: [],

    achievements: [],

    prestige: {
      points: ZERO_SD,
      totalPointsEarned: ZERO_SD,
      rebirthCount: 0,
      upgrades: [],
      milestones: [],
      perks: []
    },

    eventState: {
      activeEvents: [],
      cooldowns: {},
      pendingChoices: [],
      totalTicks: 0
    },

    loans: {
      loans: [],
      creditScore: 50,
      creditScoreFactors: { paymentHistory: 10, creditUtilization: 30, creditAge: 0, creditMix: 0, newCredit: 10 },
      loanHistory: [],
      totalTicksWithCredit: 0,
      recentApplications: [],
      totalLoansTaken: 0,
      totalLoansRepaidOnTime: 0,
      totalLoansDefaulted: 0,
      totalInterestPaidEver: ZERO_SD
    },
    deposits: {
      deposits: [],
      depositHistory: [],
      totalDeposited: ZERO_SD,
      totalInterestEarnedEver: ZERO_SD,
      totalDepositsOpened: 0,
      totalDepositsMatured: 0,
      totalEarlyWithdrawals: 0
    },

    blackmarket: {
      totalDealsCompleted: 0,
      totalDealsFailed: 0,
      reputationPoints: 0,
      heat: 0,
      dealCooldowns: {},
      lastDealRotationTick: 0,
      nextRotationTick: 0,
      contactStates: [],
      activeEffects: [],
      investigations: [],
      totalCashSpent: ZERO_SD,
      totalCashEarned: ZERO_SD,
      totalHeatAccumulated: 0,
      totalInvestigations: 0,
      totalFinesPaid: ZERO_SD,
      lastTickProcessed: 0,
      activityLog: [],
      availableDeals: [],
    },

    vault: {
      items: [],
      storedCash: ZERO_SD,
      capacityUpgrades: 0,
      totalItemsStored: 0,
      totalItemsSold: 0,
      totalSaleRevenue: ZERO_SD,
      totalCashDeposited: ZERO_SD,
      totalCashWithdrawn: ZERO_SD,
    },

    shop: {
      listings: [],
      purchasedUniqueIds: [],
      lastRefreshTick: 0,
      lastFullRestockTick: 0,
      totalItemsBought: 0,
      totalCashSpentOnPurchases: ZERO_SD,
      totalItemsSoldToShop: 0,
      totalCashFromSales: ZERO_SD,
      uniqueItemsBought: 0,
      bestDeal: ZERO_SD,
      totalItemsRestored: 0,
      totalRestorationCashSpent: ZERO_SD,
      totalAuctionRevenue: ZERO_SD,
      totalAuctionsCompleted: 0,
      demands: [],
      lastDemandTick: 0,
      restorationSlotCount: 1,
      restorationSlots: [null],
      activeAuctions: [],
      auctionHistory: [],
    },

    settings: {
      locale: 'en',
      autoSaveInterval: 30,
      offlineEfficiency: 0.5,
      offlineMaxHours: 24,
      offlineProgress: true,
      soundVolume: 50,
      musicVolume: 30,
      notificationsEnabled: true,
      numberFormat: 'short',
      theme: 'dark',
      animationSpeed: 1.0,
      lotteryDrawSpeed: 1.0,
      lotteryMultiDraw: 1,
      cloudSaveEnabled: false,
      gistId: null,
      buyAmount: 1,
      confirmBigPurchases: true,
      bigPurchaseThreshold: 50,
      confirmPrestige: true,
      showTooltips: true,
      particleEffects: true,
      marketUpdateInterval: 50,
      pinnedStockId: null,
      pinnedCryptoId: null
    }
  }
}
