/**
 * Database schema — TypeScript interfaces for the full game save state
 *
 * This file defines the "shape" of the savegame.json file persisted by LowDB.
 * All Decimal values are stored as SerializedDecimal { m, e }.
 * Version field enables forward-compatible migrations.
 *
 * IMPORTANT: The actual save format is dynamically generated by
 * `collectGameState()` in useAutoSave.ts. This schema serves as documentation
 * and for the createDefaultSave() factory. The renderer stores drive the
 * true data shapes. If you update store state structures, update collectGameState()
 * and initGame() accordingly — the schema types here are advisory.
 */

// ─── Serialized Decimal (for JSON persistence) ─────────────────────

export interface SD {
  m: number
  e: number
}

// ─── Player ─────────────────────────────────────────────────────────

export interface LoanSave {
  id: string
  principal: SD
  remaining: SD
  annualRate: number
  ticksActive: number
}

export interface PlayerSave {
  cash: SD
  totalCashEarned: SD
  totalCashSpent: SD
  /** Total prestige points (persisted across rebirths) */
  prestigePoints: SD
  /** Total rebirth count */
  rebirthCount: number
  /** XP / level for the player character */
  level: number
  xp: SD
  xpToNextLevel: SD
  /** Outstanding loans */
  loans: LoanSave[]
  /** Pre-computed net worth */
  netWorth: SD
}

// ─── Businesses ─────────────────────────────────────────────────────

export interface BusinessSave {
  id: string
  name: string
  description: string
  icon: string
  category: string
  // Operational levers
  employees: number
  pricePerUnit: number
  marketingBudget: number
  quality: number
  // Fixed from definition
  outputPerEmployee: number
  baseSalary: number
  baseRent: number
  supplyCostPerUnit: number
  optimalPrice: number
  baseCustomers: number
  elasticity: number
  sectorMultiplier: number
  qualityUpgradeCost: SD
  purchasePrice: SD
  // Tracked stats
  totalRevenue: SD
  totalCosts: SD
  totalProfit: SD
  avgProfitPerTick: SD
  ticksOwned: number
}

// ─── Jobs ───────────────────────────────────────────────────────────

export interface ActiveJobSave {
  id?: string
  defId: string
  experienceLevel: number
  ticksWorked: number
  active: boolean
}

export interface JobsSave {
  unlockedJobs: ActiveJobSave[]
}

// ─── Economy ────────────────────────────────────────────────────────

export interface EconomySave {
  inflationRate: number
  inflationIndex: number
  interestRate: number
  consumerConfidence: number
  wageIndex: number
  cyclePhase: string
  cycleTicksElapsed: number
  cyclePhaseDuration: number
  totalTicks: number
  taxRate: number
}

// ─── Stocks ─────────────────────────────────────────────────────────

export interface PortfolioPositionSave {
  assetId: string
  shares: number
  averageBuyPrice: number
  totalInvested: SD
}

export interface StockSave {
  portfolio: PortfolioPositionSave[]
  /** Market simulator serialized state */
  marketState: unknown
  totalRealizedProfit: SD
  totalDividendsEarned: SD
}

// ─── Crypto ─────────────────────────────────────────────────────────

export interface CryptoHoldingSave {
  assetId: string
  amount: number
  averageBuyPrice: number
  totalInvested: SD
}

export interface CryptoSave {
  wallet: CryptoHoldingSave[]
  marketState: unknown
  totalRealizedProfit: SD
}

// ─── Real Estate ────────────────────────────────────────────────────

export interface PropertySave {
  id: string
  locationId: string
  upgradeLevel: number
  purchasePrice: SD
  currentValue: SD
  baseRent: SD
  ownedSinceTick: number
  totalRentEarned: SD
}

export interface RealEstateSave {
  properties: PropertySave[]
  totalRentEarned: SD
  totalPropertyValue: SD
}

// ─── Startups ───────────────────────────────────────────────────────

export interface StartupInvestmentSave {
  id: string
  startupId: string
  investedAmount: SD
  investedAtTick: number
  /** Ticks until resolution */
  maturityTicks: number
  /** Current status */
  status: 'active' | 'succeeded' | 'failed' | 'exited'
  returnMultiplier: number
}

export interface StartupSave {
  investments: StartupInvestmentSave[]
  totalInvested: SD
  totalReturned: SD
}

// ─── Gambling ───────────────────────────────────────────────────────

export interface GamblingSave {
  totalBet: SD
  totalWon: SD
  totalLost: SD
  gamesPlayed: number
  biggestWin: SD
  biggestLoss: SD
  /** Per mini-game stats */
  gameStats: Record<string, { played: number; won: number; netProfit: SD }>
}

// ─── Upgrades / Skill tree ──────────────────────────────────────────

export interface UpgradeNodeSave {
  id: string
  level: number
  maxLevel: number
  purchased: boolean
}

export interface UpgradeSave {
  nodes: UpgradeNodeSave[]
}

// ─── Achievements ───────────────────────────────────────────────────

export interface AchievementSave {
  id: string
  unlocked: boolean
  unlockedAtTick: number | null
}

// ─── Prestige ───────────────────────────────────────────────────────

export interface PrestigeUpgradeSave {
  id: string
  level: number
}

export interface PrestigeSave {
  points: SD
  totalPointsEarned: SD
  rebirthCount: number
  upgrades: PrestigeUpgradeSave[]
  /** Multiplier derived from prestige tree */
  globalMultiplier: SD
}

// ─── Events ─────────────────────────────────────────────────────────

export interface EventsSave {
  activeEvents: Array<{
    eventId: string
    ticksRemaining: number
    startedAt: number
    effects: Array<{ type: string; value: number; target?: string }>
  }>
  cooldowns: Record<string, number>
  pendingChoices: string[]
  totalTicks: number
}

// ─── Settings ───────────────────────────────────────────────────────

export interface SettingsSave {
  /** Auto-save interval in seconds */
  autoSaveInterval: number
  /** Offline progress efficiency override */
  offlineEfficiency: number
  /** Max offline hours */
  offlineMaxHours: number
  /** Enable offline progress */
  offlineProgress: boolean
  /** Sound volume 0-100 */
  soundVolume: number
  /** Music volume 0-100 */
  musicVolume: number
  /** Enable notifications */
  notificationsEnabled: boolean
  /** Number format: 'short' (1.23M) | 'scientific' (1.23e6) | 'engineering' (1.23E6) */
  numberFormat: 'short' | 'scientific' | 'engineering'
  /** Theme: 'dark' | 'light' */
  theme: 'dark' | 'light'
  /** Animation speed multiplier (0.5, 1.0, 2.0) */
  animationSpeed: number
  /** GitHub PAT for cloud saves (encrypted, stored separately) */
  cloudSaveEnabled: boolean
  /** Gist ID for cloud saves */
  gistId: string | null
  /** Buy amount mode */
  buyAmount: 1 | 10 | 25 | 100 | 'max'
  /** Show confirmation dialogs for big purchases */
  confirmBigPurchases: boolean
  /** Threshold for "big purchase" confirmation (as a % of total cash) */
  bigPurchaseThreshold: number
  /** Confirm before prestige */
  confirmPrestige: boolean
  /** Show tooltips on hover */
  showTooltips: boolean
  /** Particle/visual effects */
  particleEffects: boolean
  /** Market update frequency in game ticks */
  marketUpdateInterval: number
}

// ─── Root Save Schema ───────────────────────────────────────────────

export interface GameSave {
  /** Schema version for migrations */
  version: number
  /** Timestamp of this save (ms since epoch) */
  savedAt: number
  /** Total ticks played */
  totalTicks: number
  /** Total real-time played (seconds) */
  totalPlayTime: number

  player: PlayerSave
  businesses: BusinessSave[]
  jobs: JobsSave
  economy: EconomySave

  // Stocks — flat structure matching autoSave output
  stockPortfolio: PortfolioPositionSave[]
  stockStats: { totalRealizedProfit: SD; totalDividendsEarned: SD }
  stockMarketState: unknown

  // Crypto — flat structure matching autoSave output
  cryptoWallet: CryptoHoldingSave[]
  cryptoStats: { totalRealizedProfit: SD }
  cryptoMarketState: unknown

  realEstate: PropertySave[]
  startups: StartupInvestmentSave[]
  gambling: GamblingSave
  upgrades: UpgradeNodeSave[]
  achievements: AchievementSave[]
  prestige: PrestigeSave
  events: EventsSave
  settings: SettingsSave
}

/** Current schema version. Increment when making breaking changes. */
export const CURRENT_SAVE_VERSION = 2

// ─── Default / factory ──────────────────────────────────────────────

const ZERO_SD: SD = { m: 0, e: 0 }
const ONE_SD: SD = { m: 1, e: 0 }

export function createDefaultSave(): GameSave {
  return {
    version: CURRENT_SAVE_VERSION,
    savedAt: Date.now(),
    totalTicks: 0,
    totalPlayTime: 0,

    player: {
      cash: { m: 5, e: 1 }, // $50 starting cash
      totalCashEarned: { m: 5, e: 1 }, // Match store default
      totalCashSpent: ZERO_SD,
      prestigePoints: ZERO_SD,
      rebirthCount: 0,
      level: 1,
      xp: ZERO_SD,
      xpToNextLevel: { m: 1, e: 2 }, // 100
      loans: [],
      netWorth: { m: 5, e: 1 }
    },

    businesses: [],

    jobs: {
      unlockedJobs: []
    },

    economy: {
      inflationRate: 0.02,
      inflationIndex: 1.0,
      interestRate: 0.05,
      consumerConfidence: 1.0,
      wageIndex: 1.0,
      cyclePhase: 'expansion',
      cycleTicksElapsed: 0,
      cyclePhaseDuration: 3000,
      totalTicks: 0,
      taxRate: 0.15
    },

    stockPortfolio: [],
    stockStats: {
      totalRealizedProfit: ZERO_SD,
      totalDividendsEarned: ZERO_SD
    },
    stockMarketState: null,

    cryptoWallet: [],
    cryptoStats: {
      totalRealizedProfit: ZERO_SD
    },
    cryptoMarketState: null,

    realEstate: [],

    startups: [],

    gambling: {
      totalBet: ZERO_SD,
      totalWon: ZERO_SD,
      totalLost: ZERO_SD,
      gamesPlayed: 0,
      biggestWin: ZERO_SD,
      biggestLoss: ZERO_SD,
      gameStats: {}
    },

    upgrades: [],

    achievements: [],

    prestige: {
      points: ZERO_SD,
      totalPointsEarned: ZERO_SD,
      rebirthCount: 0,
      upgrades: [],
      globalMultiplier: ONE_SD
    },

    events: {
      activeEvents: [],
      cooldowns: {},
      pendingChoices: [],
      totalTicks: 0
    },

    settings: {
      autoSaveInterval: 30,
      offlineEfficiency: 0.5,
      offlineMaxHours: 24,
      offlineProgress: true,
      soundVolume: 50,
      musicVolume: 30,
      notificationsEnabled: true,
      numberFormat: 'short',
      theme: 'dark',
      animationSpeed: 1.0,
      cloudSaveEnabled: false,
      gistId: null,
      buyAmount: 1,
      confirmBigPurchases: true,
      bigPurchaseThreshold: 50,
      confirmPrestige: true,
      showTooltips: true,
      particleEffects: true,
      marketUpdateInterval: 50
    }
  }
}
